//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ariochoob1.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyFactor
    {
        public BuyFactor()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int BuyFactorId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Campany Campany { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
