//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ariochoob1.Models.DomainModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AriochoobDBEntities1 : DbContext
    {
        public AriochoobDBEntities1()
            : base("name=AriochoobDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BuyFactor> BuyFactors { get; set; }
        public DbSet<Campany> Campanies { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<SaleFactor> SaleFactors { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<GetUserWithView> GetUserWithViews { get; set; }
    
        public virtual ObjectResult<GetUserInf_Result> GetUserInf()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserInf_Result>("GetUserInf");
        }
    }
}
