//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ariochoob1.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleFactor
    {
        public SaleFactor()
        {
            this.Users = new HashSet<User>();
        }
    
        public int SaleFactorId { get; set; }
        public System.DateTime BuyDate { get; set; }
        public string FillowCode { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public decimal Price { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
