//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ariochoob1.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.SaleFactors = new HashSet<SaleFactor>();
            this.SaleFactors1 = new HashSet<SaleFactor>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public bool Gender { get; set; }
        public byte Status { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<SaleFactor> SaleFactors { get; set; }
        public virtual ICollection<SaleFactor> SaleFactors1 { get; set; }
    }
}
